export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_POSITION = 'UPDATE_NOTE_POSITION';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
export const TOGGLE_NOTE_CHILDREN = 'TOGGLE_NOTE_CHILDREN';

export const IMPORT_OPML = 'IMPORT_OPML';
